title: Copenhagen Bioscience PhD Programme
logo: /Figures/cbpp_logo.png
description: Information on getting starting before arriving in Copenhagen.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal